name: Automatic Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.125.4'
          extended: true

      - name: Generate
        run: |
          hugo

      - name: Setup Tencent Cloud COSCLI
        run: |
          curl -sSL -o coscli https://github.com/tencentyun/coscli/releases/download/v1.0.6/coscli-v1.0.6-linux-amd64
          chmod +x coscli
          ./coscli --version

      - name: Write cos.yaml
        run: |
          echo "${{ secrets.COS_YAML }}" > cos.yaml

      - name: Deploy to Tencent Cloud COS
        run: |
          ./coscli sync -r _book cos://${{ secrets.COS_BUCKET_NAME }}/missing -c cos.yaml

