name: Automatic Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python and PyPI
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.125.4'
          extended: true

      - name: Run `utils/create_image_renderer.py`
        run: |
          python utils/create_image_renderer.py

      - name: Generate
        run: |
          hugo --minify 

      - name: Run `utils/move_images.py`
        run: |
          python utils/move_images.py

      - name: Install Tencent Cloud COSCMD
        run: |
          pip install coscmd

      - name: Configure COSCMD
        run: |
          coscmd config -a ${{ secrets.COS_SECRET_ID }} -s ${{ secrets.COS_SECRET_KEY }} -b ${{ secrets.COS_BUCKET_NAME }} -r ap-guangzhou

      - name: Deploy to Tencent Cloud COS (Main)
        run: |
          coscmd upload -rs --delete -f _book missing

      - name: Deploy to Tencent Cloud COS (Images)
        run: |
          coscmd -b ${{ secrets.COS_BUCKET_NAME_STATIC }} -r ap-guangzhou upload -rs --delete -f _images images

