name: Reject Pull Requests on Content

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    paths:
      - 'content/**'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Write a comment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/issues/{issue_number}/comments
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          issue_number: ${{ github.event.pull_request.number }}
          body: "您好，感谢您的贡献！很抱歉，为了控制文章的质量和行文风格，**我们不接受直接针对正文、图片部分（位于 `content` 目录下）的拉取请求（pull request），请您谅解**。\n\n您可以将建议、意见发送邮件到 [missing@criwits.top](mailto:missing@criwits.top)，或在本仓库中提交议题（issue）。"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Close PR
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{owner}/{repo}/pulls/{pull_number}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pull_number: ${{ github.event.pull_request.number }}
          state: closed
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }} 