name: Reject Pull Requests on Content

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR source branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Check if `content` directory is modified
        id: check_content
        run: |
          if git diff --name-only origin/${{ github.event.pull_request.base.ref }} | grep -q '^content/'; then
            echo "::set-output name=content::true"
          else
            echo "::set-output name=content::false"
          fi

      - name: Close PR if necessary
        if: steps.check_content.outputs.content == 'true'
        - uses: crondaemon/close-pr@v1
        with:
          comment: "您好，感谢您的贡献！很抱歉，为了控制文章的质量和行文风格，**我们不接受直接针对正文、图片部分（位于 `content` 目录下）的拉取请求（Pull Request），请您谅解**。\n\n您可以将建议、意见发送邮件到 [missing@criwits.top](mailto:missing@criwits.top)，或在本仓库中提交议题（Issue）。"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}